apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.name }}
type: Opaque
stringData:
  kc_bootstrap_admin_username: "{{ .Values.keycloak.secrets.kc_bootstrap_admin_username }}"
  kc_bootstrap_admin_password: "{{ .Values.keycloak.secrets.kc_bootstrap_admin_password }}"
  kc_db: "{{ .Values.keycloak.secrets.kc_db }}"