apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql_db.name }}
type: Opaque
stringData:
  hostname: "{{ .Values.postgresql_db.secrets.hostname }}"
  db: "{{ .Values.postgresql_db.secrets.db }}"
  username: "{{ .Values.postgresql_db.secrets.username }}"
  password: "{{ .Values.postgresql_db.secrets.password }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.notification.name }}
type: Opaque
stringData:
  smtp_username: "{{ .Values.notification.secrets.smtp.username }}"
  smtp_password: "{{ .Values.notification.secrets.smtp.password }}"
  twilio_account_sid: "{{ .Values.notification.secrets.twilio.account_sid }}"
  twilio_auth_token: "{{ .Values.notification.secrets.twilio.auth_token }}"
  twilio_phone_number: "{{ .Values.notification.secrets.twilio.phone_number }}"