apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql_db.name }}
type: Opaque
stringData:
  hostname: "{{ .Values.postgresql_db.secrets.hostname }}"
  db: "{{ .Values.postgresql_db.secrets.db }}"
  username: "{{ .Values.postgresql_db.secrets.username }}"
  password: "{{ .Values.postgresql_db.secrets.password }}"